apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: codegen-test1
  janus-idp.io/tekton: codegen-test1
  backstage.io/kubernetes-id: codegen-test1
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegen-test1
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
